### ISSUE TITLE
DFX

### ISSUE THREAD

**Issue by Feorice** [CartBlanche/Siege-of-Avalon-Open-Source#1]
Documentation on the DigitalFX drivers would be appreciated, If at all possible.

**Comment by CartBlanche** [comment]
@Feorice DigitalFX was a 3rd party GFX library. I don't believe they exist anymore. It just simpflied a few of the effects in the game. These days that work would probably be farmed off to some pixel shaders.

PS. Sorry about the late reply. I'm seriously considering restarting the port to C#.

**Comment by Feorice** [comment]
The main reason I had asked about the DFX drivers was because I noticed it was used to pack and unpack the custom file format used for the assets. Unless I'm wrong about that. I did manage to find a forum a while back which provided some tools for viewing, unpacking, and packing your own assets using that format. But I didn't want to rely on that. I'm assuming that with the port you probably want to make new assets anyway.

P.S. How would you feel about porting this to Java as well?
